### PR TITLE
Update to nlm 2.9.2 v2

### PR DESCRIPTION
**Pull request by jamesvillarrubia**
## Description of the change
  * This PR updates the Tika server version from 2.9.2_v1 to 2.9.2_v2 and adds new headers to the TikaFileParser.
  * New headers `X-Tika-PDFOcrStrategy` and `X-Tika-PDFExtractFontNames` have been added to the TikaFileParser for better control of the OCR and PDF parsing behavior.
  * 2.9.2_v1 failed to included necessary style attributes when computing `<p>` tags. New jar resolves this bug.

## Type of change
- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
The changes have been tested manually to ensure the Tika server works correctly with the new configuration and headers.  Additional testing is required for edge cases.

### CODE REVIEW

**Comment by jamesvillarrubia** [comment]
@ansukla As expected, there are some critical fixes in this version that I missed in the first, if you get a sec to a approve. Cheers!

**Comment by JSv4** [comment]
FWIW, I've been testing some PDFs that are broken under current main branch. Three of them are working *great* with these changes.

**Comment by bzhr** [comment]
Can this get published?

**Comment by bzhr** [comment]
Very nice, if somebody can provide an example of a docker build command that will build from the main branch, so that I can test, that would be wonderful

**Comment by Ebraheem-Alrabeea** [comment]
Hi @jamesvillarrubia,

I hope you're doing well! I wanted to ask if the new v2 contains any changes other than those listed in the comparison you posted [here](https://github.com/jamesvillarrubia/nlm-tika/compare/branch_2x...jamesvillarrubia:nlm-tika:revised_nlm?expand=1).
I plan to make some RTL fixes over NLM 2.9.2 and would appreciate your confirmation.

Thank you!

**Pull request merged**
